# This is the configuration file for catnip
# Here you can configure the stat colors,
# stat names, stat icons, distro ascii-art and more


##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username = {icon = " ", name = "user", color = "(RD)"}
hostname = {icon = " ", name = "hname", color = "(YW)"}
uptime   = {icon = " ", name = "uptime", color = "(BE)"}
distro   = {icon = " ", name = "distro", color = "(GN)"}
kernel   = {icon = " ", name = "kernel", color = "(MA)"}
desktop  = {icon = " ", name = "desktp", color = "(CN)"}
shell    = {icon = " ", name = "shell", color = "(RD)"}
colors   = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##         Distro ASCII-Art Config          ##
##############################################
[distroart]
    [distroart.default]
    alias = "catnip"

    [distroart.catnip]
    margin = [1, 2, 2]
    art    = [
        "(GN)          ⣀⣀⣠⣠⣶⠦⢴⣦⣀⣠⣀  ",
        "(GN)     ⢀⣤⣴⠿⠋⠿⠋⠁   ⠉⠉⠉⠉⣿⡇ ",
        "(GN)    ⣴⡟⠙⠁   ⡆        ⣰⡿ ",
        "(GN)  ⣰⡿⡟   ⡇ ⢸⣧⣚⡀     ⢻⡇  ",
        "(GN) ⢠⣿⠁ ⢸  ⣇⡴⠋⠉⠉     ⣰⡿⠁  ",
        "(GN) ⢸⣏  ⢸⣀⣴⠟⠛⠛⠉⠁    ⢚⣿    ",
        "(GN) ⠸⣿  ⣼⣿⠧⠤⠤⠔   ⣀⣤⡾⠛⠁    ",
        "(GN)  ⠹⣧⣾⡟⠁     ⢀⣠⣼⡿       ",
        "(GN)  ⢀⣼⠟⣼⡟⠻⠿⠛⠛⠛⠉⠁         ",
        "(GN)  ⠘⠿⠾⠏                 "
    ]

    [distroart.tux]
    margin = [2, 2, 3]
    art    = [
        "(BK)      .--.     ",
        "(BK)     |!DT!o(BK)_!DT!o (BK)|    ",
        "(BK)     |(YW):_/ (BK)|    ",
        "(BK)    /!DT!/   \\ (BK)\\   ",
        "(BK)   (!DT!|     | (BK))  ",
        "(YW)  /'!DT!|_   _/(YW)'\\  ",
        "(YW)  \\___)(BK)=(YW)(___/  "
    ]

    [distroart.arch]
    margin = [2, 2, 3]
    art    = [
        "{BE}      /\\      ",
        "{BE}     /  \\     ",
        "{BE}    /\\   \\    ",
        "{BE}   /      \\   ",
        "{BE}  /   ,,   \\  ",
        "{BE} /   |  |  -\\ ",
        "{BE}/_-''    ''-_\\"
    ]

    [distroart.archcraft]
    margin = [2, 2, 3]
    art    = [
        "{GN}      .      ",
        "{GN}     / \\     ",
        "{GN}    /\\  \\    ",
        "{GN}   /     \\   ",
        "{GN}  / , ^ , \\  ",
        "{GN} /  <   > -\\ ",
        "{GN}/_-''   ''-_\\"
    ]

    [distroart.windows]
    margin = [2, 2, 4]
    art    = [
        "[RD]       [GN]       ",
        "[RD]       [GN]       ",
        "[RD]       [GN]       ",
        "[BE]       [YW]       ",
        "[BE]       [YW]       ",
        "[BE]       [YW]       "
    ]

    [distroart.ubuntu]
    margin = [0, 2, 4]
    art    = [
        "{RD}                .-.   ",
        "{RD}        .-'````(   )  ",
        "{RD}     ,`\\ \\    `-`.    ",
        "{RD}    /   \\ '````-.   ` ",
        "{RD}  .-.  ,         `___:",
        "{RD} (   ) :          ___ ",
        "{RD}  `-`  `         ,   :",
        "{RD}    \\   / ,....-`   , ",
        "{RD}     `./ /      .-.`  ",
        "{RD}        `-....-(   )  ",
        "{RD}                `-`   "
    ]

    [distroart.manjaro]
    margin = [2, 2, 4]
    art    = [
        "<GN>        !DT!  <GN>    ",
        "<GN>        !DT!  <GN>    ",
        "<GN>   !DT!       <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    "
    ]

    [distroart.debian]
    margin = [1, 2, 3]
    art    = [
        "(RD)  , - = - ,   ",
        "(RD) =    ,,   =  ",
        "(RD)=   :°   ;  = ",
        "(RD)=   :.      = ",
        "(RD)^=    ° == °  ",
        "(RD)°=.           ",
        "(RD) ^==..        ",
        "(RD)   ^^°==..    ",
        "(RD)        ^^°=  ",
    ]