# This is the configuration file for catnip
# Here you can configure the stat colors,
# stat names, stat icons, distro ascii-art and more

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username = {icon = " ", name = "user", color = "(RD)"}
hostname = {icon = " ", name = "hname", color = "(YW)"}
uptime   = {icon = " ", name = "uptime", color = "(BE)"}
distro   = {icon = " ", name = "distro", color = "(GN)"}
kernel   = {icon = " ", name = "kernel", color = "(MA)"}
desktop  = {icon = " ", name = "desktp", color = "(CN)"}
shell    = {icon = " ", name = "shell", color = "(RD)"}
colors   = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]

[misc.figletLogos]
enable = false
color  = "(YW)"
margin = [0, 0, 0,]

##############################################
##         Distro ASCII-Art Config          ##
##############################################
[distroart]
    [distroart.default]
    alias = "catnip"

    [distroart.catnip]
    margin = [1, 2, 2]
    art    = [
        "(GN)          ⣀⣀⣠⣠⣶⠦⢴⣦⣀⣠⣀  ",
        "(GN)     ⢀⣤⣴⠿⠋⠿⠋⠁   ⠉⠉⠉⠉⣿⡇ ",
        "(GN)    ⣴⡟⠙⠁   ⡆        ⣰⡿ ",
        "(GN)  ⣰⡿⡟   ⡇ ⢸⣧⣚⡀     ⢻⡇  ",
        "(GN) ⢠⣿⠁ ⢸  ⣇⡴⠋⠉⠉     ⣰⡿⠁  ",
        "(GN) ⢸⣏  ⢸⣀⣴⠟⠛⠛⠉⠁    ⢚⣿    ",
        "(GN) ⠸⣿  ⣼⣿⠧⠤⠤⠔   ⣀⣤⡾⠛⠁    ",
        "(GN)  ⠹⣧⣾⡟⠁     ⢀⣠⣼⡿       ",
        "(GN)  ⢀⣼⠟⣼⡟⠻⠿⠛⠛⠛⠉⠁         ",
        "(GN)  ⠘⠿⠾⠏                 "
    ]

    [distroart.tux]
    margin = [2, 2, 3]
    art    = [
        "(BK)      .--.     ",
        "(BK)     |!DT!o(BK)_!DT!o (BK)|    ",
        "(BK)     |(YW):_/ (BK)|    ",
        "(BK)    /!DT!/   \\ (BK)\\   ",
        "(BK)   (!DT!|     | (BK))  ",
        "(YW)  /'!DT!|_   _/(YW)'\\  ",
        "(YW)  \\___)(BK)=(YW)(___/  "
    ]

    [distroart.arch]
    margin = [2, 2, 3]
    art    = [
        "{BE}      /\\      ",
        "{BE}     /  \\     ",
        "{BE}    /\\   \\    ",
        "{BE}   /      \\   ",
        "{BE}  /   ,,   \\  ",
        "{BE} /   |  |  -\\ ",
        "{BE}/_-''    ''-_\\"
    ]

    [distroart.archcraft]
    margin = [2, 2, 3]
    art    = [
        "{GN}      .      ",
        "{GN}     / \\     ",
        "{GN}    /\\  \\    ",
        "{GN}   /     \\   ",
        "{GN}  / , ^ , \\  ",
        "{GN} /  <   > -\\ ",
        "{GN}/_-''   ''-_\\"
    ]

    [distroart.windows]
    margin = [2, 2, 4]
    art    = [
        "[RD]       [GN]       ",
        "[RD]       [GN]       ",
        "[RD]       [GN]       ",
        "[BE]       [YW]       ",
        "[BE]       [YW]       ",
        "[BE]       [YW]       "
    ]

    [distroart.ubuntu]
    margin = [0, 2, 4]
    art    = [
        "{RD}                .-.   ",
        "{RD}        .-'````(   )  ",
        "{RD}     ,`\\ \\    `-`.    ",
        "{RD}    /   \\ '````-.   ` ",
        "{RD}  .-.  ,         `___:",
        "{RD} (   ) :          ___ ",
        "{RD}  `-`  `         ,   :",
        "{RD}    \\   / ,....-`   , ",
        "{RD}     `./ /      .-.`  ",
        "{RD}        `-....-(   )  ",
        "{RD}                `-`   "
    ]

    [distroart.manjaro]
    margin = [2, 2, 4]
    art    = [
        "<GN>        !DT!  <GN>    ",
        "<GN>        !DT!  <GN>    ",
        "<GN>   !DT!       <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    ",
        "<GN>   !DT!  <GN>   !DT!  <GN>    "
    ]

    [distroart.debian]
    margin = [1, 2, 3]
    art    = [
        "(RD)  , - = - ,   ",
        "(RD) =    ,,   =  ",
        "(RD)=   :°   ;  = ",
        "(RD)=   :.      = ",
        "(RD)^=    ° == °  ",
        "(RD)°=.           ",
        "(RD) ^==..        ",
        "(RD)   ^^°==..    ",
        "(RD)        ^^°=  ",
    ]

    [distroart.nixos]
    margin = [1, 2, 3]
    art    = [
        "{BE}     ⣀⡀  {CN}⣀⣀⡀ ⢀⣀     ",
        "{BE}    ⠈⢿⣷⡀ {CN}⠈⢿⣷⣄⣾⡿⠃    ",
        "{BE}  ⢀⣶⣶⣾⣿⣿⣶⣶⣮{CN}⣻⣿⣿⠁ {BE}⢠⡀  ",
        "{CN}     ⣩⣭⡍    ⢻⣿⣆{BE}⢠⣿⡗  ",
        "{CN}⢠⣤⣤⣤⣴⣿⠟      ⠹{BE}⣳⣿⣿⣤⣤⡄",
        "{CN}⠘⠛⠛⣿⣿⢯{BE}⣦      ⣰⣿⠟⠛⠛⠛⠃",
        "{CN}  ⢼⣿⠋{BE}⠹⣿⣧{CN}⢀⣀⣀⣀⣜⣛⣋⣀⣀⡀  ",
        "{CN}  ⠈⠃ {BE}⢀⣾⣿⣷{CN}⡻⠿⠿⢿⣿⡿⠿⠿⠁  ",
        "{BE}    ⢠⣾⡿⠙⢿⣷⡀ {CN}⠈⢿⣷⡄    ",
        "{BE}     ⠉⠁ ⠈⠉⠉  {CN}⠈⠉     "
    ]

    [distroart.fedora]
    margin = [1, 2, 3]
    art    = [
        "(WE)       _____  ",
        "(WE)     /   __)(BE)\\ ",
        "(WE)     |  /  (BE)\\ \\",
        "(BE)  __(WE)_|  |_(BE)_/ /",
        "(BE) / (WE)(_    _)(BE)_/ ",
        "(BE)/ /  (WE)|  |     ",
        "(BE)\\ \\(WE)__/  |     ",
        "(BE) \\(WE)(_____/     "

    ]

    [distroart.void]
    margin = [2, 2, 4]
    art    = [
        "(GN)    _______  ",
        "(GN) _ \\______ - ",
        "(GN)| \\  ___  \\ |",
        "(GN)| | /   \\ | |",
        "(GN)| | \\___/ | |",
        "(GN)| \\______ \\_|",
        "(GN) -_______\\   "
    ]

    [distroart.mint]
    margin = [2, 2, 4]
    art    = [
        "{CN} ___________ ",
        "{CN}|_          \\",
        "{CN}  | (WE)| _____ {CN}|",
        "{CN}  | (WE)| | | | {CN}|",
        "{CN}  | (WE)| | | | {CN}|",
        "{CN}  | (WE)\\_____/ {CN}|",
        "{CN}  \\_________/"
    ]

    [distroart.linuxmint]
    alias = "mint"

    [distroart.raspbian]
    margin = [2, 2, 3]
    art    = [
        "{GN}  __  __   ",
        "{GN} (_\\)(/_)  ",
        "{RD} (_(__)_)  ",
        "{RD}(_(_)(_)_) ",
        "{RD} (_(__)_)  ",
        "{RD}   (__)    "
    ]

    [distroart.raspberrypios]
    alias = "raspbian"

    [distroart.android]
    margin = [2, 2, 2]
    art    = [
        "{GN}  ;,           ,;  ",
        "{GN}   ';,.-----.,;'   ",
        "{GN}  ,'           ',  ",
        "{GN} /    O     O    \\ ",
        "{GN}|                 |",
        "{GN}'-----------------'"
    ]

    [distroart.gentoo]
    margin = [2, 2, 3]
    art    = [
        "{MA} _-----_   ",
        "{MA}(       \\  ",
        "{MA}\\    0   \\ ",
        "{WE} \\        )",
        "{WE} /      _/ ",
        "{WE}(     _-   ",
        "{WE}\\____-     "
    ]

    [distroart.endeavour]
    margin = [2, 2, 3]
    art    = [
        "{MA}       /\\     ",
        "{RD}     /{MA}/  \\{CN}\\   ",
        "{RD}    /{MA}/    \\{CN}\\  ",
        "{RD}  / {MA}/     _) {CN})",
        "{RD} /_{MA}/___-- {CN}__- ",
        "{CN}/____--       "
    ]

    [distroart.endeavouros]
    alias = "endeavour"

    [distroart.popos]
    margin = [1, 1, 2]
    art    = [
        "{CN}  ______             ",
        "{CN}  \\   _ \\        __  ",
        "{CN}   \\ \\ \\ \\      / /  ",
        "{CN}    \\ \\_\\ \\    / /   ",
        "{CN}     \\  ___\\  /_/    ",
        "{CN}      \\ \\    _       ",
        "{CN}     __\\_\\__(_)_     ",
        "{CN}    (___________)    "
    ]
