# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hostname", color = "(YW)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
desktop   = {icon = " ", name = "desktop", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(RD)"}
shell     = {icon = " ", name = "shell", color = "(MA)"}
# packages  = {icon = " ", name = "packages", color = "(RD)"}  # WARNING: Resource Intensive
# weather   = {icon = " ", name = "weather", color = "(BE)"} # Requires curl and an emoji font. | WARNING: Resource Intensive
# The following stats do not work on MacOS and the BSDs.
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}      # WARNING: Resource Intensive
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
# memory    = {icon = " ", name = "memory", color = "(YW)"}
# battery    = {icon = " ", name = "battery", color = "(GN)"}
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0
location = "" # Used for fetching weather; leave empty to use the location of your IP; check https://wttr.in/:help for supported location types

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/path/to/some/image.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]

