# This is the distro logos file for catnip.
# Here you can configure all distro logos 
# or add a new one.
#
# https://github.com/iinsertNameHere/catnip

##############################################
##         Distro ASCII-Art Config          ##
##############################################

### A ###
[alpine]
margin = [3, 2, 2,]
art    = [
    "{BE}    /\\ /\\    ",
    "{BE}   // \\  \\   ",
    "{BE}  //   \\  \\  ",
    "{BE} ///    \\  \\ ",
    "{BE}///      \\  \\",
]
 
[android]
margin = [2, 2, 2,]
art    = [
    "{GN}  ;,           ,;  ",
    "{GN}   ';,.-----.,;'   ",
    "{GN}  ,'           ',  ",
    "{GN} /    O     O    \\ ",
    "{GN}|                 |",
    "{GN}'-----------------'",
]

[arch]
margin = [2, 2, 3,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /\\   \\    ",
    "{BE}   /      \\   ",
    "{BE}  /   ,,   \\  ",
    "{BE} /   |  |  -\\ ",
    "{BE}/_-''    ''-_\\",
]

[archcraft]
margin = [2, 2, 3,]
art    = [
    "{GN}      .      ",
    "{GN}     / \\     ",
    "{GN}    /\\  \\    ",
    "{GN}   /     \\   ",
    "{GN}  / , ^ , \\  ",
    "{GN} /  <   > -\\ ",
    "{GN}/_-''   ''-_\\",
]

[arco]
alias = "arcolinux"
margin = [1, 2, 2,]
art    = [
    "{BE}          A          ",
    "{BE}         ooo         ",
    "{BE}        ooooo        ",
    "{BE}       ooooooo       ",
    "{BE}      ooooooooo      ",
    "{BE}     ooooo ooooo     ",
    "{BE}    ooooo   ooooo    ",
    "{BE}   ooooo     ooooo   ",
    "{BE}  ooooo  {GN}oooooooooo  ",
    "{BE} ooooo      {GN}oooooooo ",
    "{BE}ooooo          {GN}oooooo",
]

[artix]
margin = [2,2,2,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /`'.,\\    ",
    "{BE}   /     ',   ",
    "{BE}  /      ,`\\  ",
    "{BE} /   ,.'`.  \\ ",
    "{BE}/.,'`     `'.\\",
]

### B ####

### C ####
[catnip]
alias  = "default"
margin = [1, 2, 2,]
art    = [
    "(GN)          ⣀⣀⣠⣠⣶⠦⢴⣦⣀⣠⣀  ",
    "(GN)     ⢀⣤⣴⠿⠋⠿⠋⠁   ⠉⠉⠉⠉⣿⡇ ",
    "(GN)    ⣴⡟⠙⠁   ⡆        ⣰⡿ ",
    "(GN)  ⣰⡿⡟   ⡇ ⢸⣧⣚⡀     ⢻⡇  ",
    "(GN) ⢠⣿⠁ ⢸  ⣇⡴⠋⠉⠉     ⣰⡿⠁  ",
    "(GN) ⢸⣏  ⢸⣀⣴⠟⠛⠛⠉⠁    ⢚⣿    ",
    "(GN) ⠸⣿  ⣼⣿⠧⠤⠤⠔   ⣀⣤⡾⠛⠁    ",
    "(GN)  ⠹⣧⣾⡟⠁     ⢀⣠⣼⡿       ",
    "(GN)  ⢀⣼⠟⣼⡟⠻⠿⠛⠛⠛⠉⠁         ",
    "(GN)  ⠘⠿⠾⠏                 ",
]

[crux]
margin = [2, 2, 3,]
art    = [
    "{BE}    ___   ",
    "{BE}   (.· |  ",
    "{BE}   ({YW}<>{BE} |  ",
    "{BE}  / {WE}__{BE}  \\ ",
    "{BE} ( {WE}/  \\{BE} /|",
    "{YW}_/\\{WE}(__){YW}/_)",
    "{YW}\\/{BE}-____{YW}\\/ ",
]

### D ###
[debian]
margin = [1, 2, 3,]
art    = [
    "(RD)  , - = - ,   ",
    "(RD) =    ,,   =  ",
    "(RD)=   :°   ;  = ",
    "(RD)=   :.      = ",
    "(RD)^=    ° == °  ",
    "(RD)°=.           ",
    "(RD) ^==..        ",
    "(RD)   ^^°==..    ",
    "(RD)        ^^°=  ",
]

[devuan]
margin = [2, 2, 2,]
art    = [
    "..:::.      ",
    "    ..-==-  ",
    "        .+#:",
    "         =@@",
    "      :+%@#:",
    ".:=+#@@%*:  ",
    "@@@@#=:     ",
]

### E ###
[elementary]
alias = "elementaryos"
margin = [2, 2, 3,]
art    = [
    "{WE}  _______  ",
    "{WE} / ____  \\ ",
    "{WE}/  |  /  /\\",
    "{WE}|__\\ /  / |",
    "{WE}\\   /__/  /",
    "{WE} \\_______/ ",
]

[endeavour]
alias = "endeavouros"
margin = [2, 2, 3,]
art    = [
    "{MA}       /\\     ",
    "{RD}     /{MA}/  \\{CN}\\   ",
    "{RD}    /{MA}/    \\{CN}\\  ",
    "{RD}  / {MA}/     _) {CN})",
    "{RD} /_{MA}/___-- {CN}__- ",
    "{CN}/____--       ",
]

### F ###
[fedora]
margin = [1, 2, 3,]
art    = [
    "(WE)       _____  ",
    "(WE)     /   __)(BE)\\ ",
    "(WE)     |  /  (BE)\\ \\",
    "(BE)  __(WE)_|  |_(BE)_/ /",
    "(BE) / (WE)(_    _)(BE)_/ ",
    "(BE)/ /  (WE)|  |     ",
    "(BE)\\ \\(WE)__/  |     ",
    "(BE) \\(WE)(_____/     ",

]

### G ###
[garuda]
margin = [3, 2, 3,]
art    = [
    "(MA)     .----.   ",
    "(MA)   .'   ,  '. ",
    "(MA) .'    '-----|",
    "(MA)'.   -----,   ",
    "(MA)  '.____.'    ",
]

[gentoo]
margin = [2, 2, 3,]
art    = [
    "{MA} _-----_   ",
    "{MA}(       \\  ",
    "{MA}\\    0   \\ ",
    "{WE} \\        )",
    "{WE} /      _/ ",
    "{WE}(     _-   ",
    "{WE}\\____-     ",
]

[guix]
margin = [3, 2, 3,]
art    = [
    "{YW}|.__          __.| ",
    "{YW}|__ \\        / __| ",
    "{YW}   \\ \\      / /    ",
    "{YW}    \\ \\    / /     ",
    "{YW}     \\ \\  / /      ",
    "{YW}      \\ \\/ /       ",
    "{YW}       \\__/        ",
]

### H ###
[hyperbola]
margin = [2, 2, 3]
art = [
    "    |`__.`/  ",
    "    \\____/   ",
    "    .--.     ",
    "   /    \\    ",
    "  /  ___ \\   ",
    " / .`   `.\\  ",
    "/.`      `.\\ ",
]

### I ###

### J ###

### K ###
[kali]
margin = [0, 1, 2]
art    = [
    "{BE}        ⢀ ⡀        ",
    "{BE}     ⢀⡀⢀⡀⢣⡐⣄       ",
    "{BE}  ⢤⣬⣿⣿⣿⣿⣿⣶⣿⣮⣷⣄     ",
    "{BE} ⢴⣿⣿⠛⠉  ⠈⠉⠻⣿⣿⣿⣷⣄   ",
    "{BE}⢠⣿⣿⡇        ⢿⣿⣦⣿⣦  ",
    "{BE} ⡸⣿⣷⡀        ⠙⠻⣿⣷⡀ ",
    "{BE}  ⠸⠻⣿⣦⡀        ⠈⢻⣿⠇",
    "{BE}     ⠉⠛⠷⣦⣄⡀     ⠈⠁ ",
    "{BE}         ⠉⠛⢷⣄      ",
    "{BE}            ⠈⢿     ",
]

### L ###

### M ###
[manjaro]
margin = [2, 2, 4,]
art    = [
    "<GN>        !DT!  <GN>    ",
    "<GN>        !DT!  <GN>    ",
    "<GN>   !DT!       <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
]

[mint]
alias = "linuxmint"
margin = [2, 2, 4,]
art    = [
    "{CN} ___________ ",
    "{CN}|_          \\",
    "{CN}  | (WE)| _____ {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)\\_____/ {CN}|",
    "{CN}  \\_________/",
]

[mx]
margin = [2, 2, 3,]
art    = [
    "{WE}    \\\\  /  ",
    "{WE}     \\\\/   ",
    "{WE}      \\\\   ",
    "{WE}   /\\/ \\\\  ",
    "{WE}  /  \\  /\\ ",
    "{WE} /    \\/  \\",
    "{WE}/__________\\",
]

### N ###
[none]
margin = [0, 0, 0,]
art = [""]

[nixos]
margin = [1, 2, 3,]
art    = [
    "{BE}     ⣀⡀  {CN}⣀⣀⡀ ⢀⣀     ",
    "{BE}    ⠈⢿⣷⡀ {CN}⠈⢿⣷⣄⣾⡿⠃    ",
    "{BE}  ⢀⣶⣶⣾⣿⣿⣶⣶⣮{CN}⣻⣿⣿⠁ {BE}⢠⡀  ",
    "{CN}     ⣩⣭⡍    ⢻⣿⣆{BE}⢠⣿⡗  ",
    "{CN}⢠⣤⣤⣤⣴⣿⠟      ⠹{BE}⣳⣿⣿⣤⣤⡄",
    "{CN}⠘⠛⠛⣿⣿⢯{BE}⣦      ⣰⣿⠟⠛⠛⠛⠃",
    "{CN}  ⢼⣿⠋{BE}⠹⣿⣧{CN}⢀⣀⣀⣀⣜⣛⣋⣀⣀⡀  ",
    "{CN}  ⠈⠃ {BE}⢀⣾⣿⣷{CN}⡻⠿⠿⢿⣿⡿⠿⠿⠁  ",
    "{BE}    ⢠⣾⡿⠙⢿⣷⡀ {CN}⠈⢿⣷⡄    ",
    "{BE}     ⠉⠁ ⠈⠉⠉  {CN}⠈⠉     ",
]

### O ###
[opensuse]
margin = [0, 0, 2,]
art    = [
    "!DT!           .;ldkO0000Okdl;.           ",
    "!DT!       .;d00xl:^''''''^:ok00d;.       ",
    "!DT!     .d00l'                'o00d.     ",
    "!DT!   .d0Kd'  (GN)Okxol:;,.          !DT!:O0d.   ",
    "!DT!  .OK(GN)KKK0kOKKKKKKKKKKOxo:,      !DT!lK0.  ",
    "!DT! ,0K(GN)KKKKKKKKKKKKKKKOP^!DT!,,,(GN)^dx:    !DT!;OO, ",
    "!DT!.OK(GN)KKKKKKKKKKKKKKKk'!DT!.oOPPb.(GN)'Ok.   !DT!cKO.",
    "!DT!:KK(GN)KKKKKKKKKKKKKKK: !DT!kKx..dd (GN)lKd   !DT!'OK:",
    "!DT!dKK(GN)KKKKKKKKKOxOKKKd !DT!^OKKKO' (GN)kKKc   !DT!dKd",
    "!DT!dKK(GN)KKKKKKKKKK;.;oOKx,..!DT!^(GN)..;kKKKO.  !DT!dKd",
    "!DT!:KK(GN)KKKKKKKKKK0o;...^cdxxOK0O/^^'  !DT!.OK:",
    "!DT! kKK(GN)KKKKKKKKKKKKKOx;,,......,;od  !DT!lKk ",
    "!DT! '0K(GN)KKKKKKKKKKKKKKKKKKKK00KKOo^  !DT!c00' ",
    "!DT!  'kK(GN)KKOxddxkOO00000Okxoc;''   !DT!.dKk'  ",
    "!DT!    l0Ko.                    .c00l'   ",
    "!DT!     'l0Kk:.              .;xK0l'     ",
    "!DT!        'lkK0xl:;,,,,;:ldO0kl'        ",
    "!DT!            '^:ldxkkkkxdl:^'          "
]

### P ###
[parabola]
margin = [2, 2, 2,]
art    = [
    "  __ __ __  _  ",
    "`_//_//_/ / `. ",
    "          /  .`",
    "         / .`  ",
    "        /.`    ",
    "       /`      ",
]

[pop]
alias = "popos, pop_os"
margin = [1, 1, 2,]
art    = [
    "{CN}  ______             ",
    "{CN}  \\   _ \\        __  ",
    "{CN}   \\ \\ \\ \\      / /  ",
    "{CN}    \\ \\_\\ \\    / /   ",
    "{CN}     \\  ___\\  /_/    ",
    "{CN}      \\ \\    _       ",
    "{CN}     __\\_\\__(_)_     ",
    "{CN}    (___________)    ",
]

[postmarketos]
margin = [2, 2, 2,]
art    = [
    "{GN}        /\\        ",
    "{GN}       /  \\       ",
    "{GN}      /    \\      ",
    "{GN}      \\__   \\     ",
    "{GN}    /\\__ \\  _\\    ",
    "{GN}   /   /  \\/ __   ",
    "{GN}  /   / ____/  \\  ",
    "{GN} /    \\ \\       \\ ",
    "{GN}/_____/ /________\\",
]

[pureos]
margin = [3, 2, 2,]
art    = [
    " _____________ ",
    "|  _________  |",
    "| |         | |",
    "| |         | |",
    "| |_________| |",
    "|_____________|",
]

### Q ###

### R ###
[raspbian]
alias = "raspberrypios"
margin = [2, 2, 3,]
art    = [
    "{GN}  __  __   ",
    "{GN} (_\\)(/_)  ",
    "{RD} (_(__)_)  ",
    "{RD}(_(_)(_)_) ",
    "{RD} (_(__)_)  ",
    "{RD}   (__)    ",
]

[rocky]
margin = [1, 2, 3]
art    = [
    "{GN}    `-/+++++++++/-.`     ",
    "{GN} `-+++++++++++++++++-`   ",
    "{GN}.+++++++++++++++++++++.  ",
    "{GN}-+++++++++++++++++++++++.",
    "{GN}+++++++++++++++/-/+++++++",
    "{GN}+++++++++++++/.   ./+++++",
    "{GN}+++++++++++:.       ./+++",
    "{GN}+++++++++:`   `:/:`   .:/",
    "{GN}-++++++:`   .:+++++:`    ",
    "{GN} .+++-`   ./+++++++++:`  ",
    "{GN}  `-`   ./+++++++++++-   ",
    "{GN}       -+++++++++:-.`    ",
]

### S ###
[slackware]
margin = [2, 2, 3,]
art    = [
    "{BE}   ________  ",
    "{BE}  /  ______| ",
    "{BE}  | |______  ",
    "{BE}  \\______  \\ ",
    "{BE}   ______| | ",
    "{BE}| |________/ ",
    "{BE}|____________",
]

[sourcemage]
margin = [0, 2, 3]
art    = [
    "       :ymNMNho.              ",
    ".+sdmNMMMMMMMMMMy`            ",
    ".-::/yMMMMMMMMMMMm-           ",
    "      sMMMMMMMMMMMm/          ",
    "     /NMMMMMMMMMMMMMm:        ",
    "    .MMMMMMMMMMMMMMMMM:       ",
    "    `MMMMMMMMMMMMMMMMMN.      ",
    "     NMMMMMMMMMMMMMMMMMd      ",
    "     mMMMMMMMMMMMMMMMMMMo     ",
    "     hhMMMMMMMMMMMMMMMMMM.    ",
    "     .`/MMMMMMMMMMMMMMMMMs    ",
    "        :mMMMMMMMMMMMMMMMN`   ",
    "         `sMMMMMMMMMMMMMMM+   ",
    "           /NMMMMMMMMMMMMMN`  ",
    "             oMMMMMMMMMMMMM+  ",
    "          ./sd.-hMMMMMMMMmmN` ",
    "      ./+oyyyh- `MMMMMMMMMmNh ",
    "                 sMMMMMMMMMmmo",
    "                 `NMMMMMMMMMd:",
    "                  -dMMMMMMMMMo",
    "                    -shmNMMms.",
]

### T ###
[tux]
margin = [2, 2, 3,]
art    = [
    "(BK)      .--.     ",
    "(BK)     |!DT!o(BK)_!DT!o (BK)|    ",
    "(BK)     |(YW):_/ (BK)|    ",
    "(BK)    /!DT!/   \\ (BK)\\   ",
    "(BK)   (!DT!|     | (BK))  ",
    "(YW)  /'!DT!|_   _/(YW)'\\  ",
    "(YW)  \\___)(BK)=(YW)(___/  ",
]

### U ###
[ubuntu]
margin = [0, 2, 4,]
art    = [
    "{RD}                .-.   ",
    "{RD}        .-'````(   )  ",
    "{RD}     ,`\\ \\    `-`.    ",
    "{RD}    /   \\ '````-.   ` ",
    "{RD}  .-.  ,         `___:",
    "{RD} (   ) :          ___ ",
    "{RD}  `-`  `         ,   :",
    "{RD}    \\   / ,....-`   , ",
    "{RD}     `./ /      .-.`  ",
    "{RD}        `-....-(   )  ",
    "{RD}                `-`   ",
]

### V ###
[venom]
margin = [1, 2, 3,]
art    = [
    "{WE} ++**               ",
    "{WE}  *===**====+*      ",
    "{WE}   *====*   +===+   ",
    "{WE} *==*+===*    *===* ",
    "{WE}*===* *===+    *===*",
    "{WE}*===*  +===+   *===*",
    "{WE}*===*   +===*  *===*",
    "{WE} *===*    *===+*==* ",
    "{WE}   +===+   *===+=*  ",
    "{WE}      *+====**===*  ",
    "{WE}               **++ ",
]

[void]
margin = [2, 2, 4,]
art    = [
    "(GN)    _______  ",
    "(GN) _ \\______ - ",
    "(GN)| \\  ___  \\ |",
    "(GN)| | /   \\ | |",
    "(GN)| | \\___/ | |",
    "(GN)| \\______ \\_|",
    "(GN) -_______\\   ",
]

### W ###

### X ###

### Y ###

### Z ###
[zorin]
margin = [1, 1, 2]
art    = [
    "(BE)    ⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆    ",
    "(BE)   ⠐⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠂   ",
    "(BE)                    ",
    "(BE) ⣴⣿⣿⣿⣿⣿⣿⣿⡿⠟⠋⠁  ⣀⣤⣶⣦ ",
    "(BE)⢼⣿⣿⣿⣿⣿⠿⠋⠁  ⢀⣠⣶⣿⣿⣿⣿⣿⡇",
    "(BE) ⠹⣿⠛⠉   ⣀⣴⣾⣿⣿⣿⣿⣿⣿⣿⠟ ",
    "(BE)                    ",
    "(BE)   ⠠⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⠄   ",
    "(BE)    ⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏    ",
]
