# This is the distro logos file for catnap.
# Here you can configure all distro logos 
# or add a new one.
#
# https://github.com/iinsertNameHere/catnap

##############################################
##         Distro ASCII-Art Config          ##
##############################################

### A ###
[alpine]
margin = [3, 2, 2,]
art    = [
    "{BE}    /\\ /\\    ",
    "{BE}   // \\  \\   ",
    "{BE}  //   \\  \\  ",
    "{BE} ///    \\  \\ ",
    "{BE}///      \\  \\",
]

[amogos]
margin = [1, 2, 3]
art    = [
    "{RD}      -///:.   ",
    "{RD}     smhhhhmh\\`",
    "{RD}    :NA{BE}mogO{RD}SNs ",
  	"{RD}    hNNmmmmNNN ",
		"{RD}    NNNNNNNNNN ",
		"{RD}   :NNNNNNNNNN ",
		"{RD}   mNNssussNNN ",
		"{RD}  sNn:    sNNo ",
		"{RD}+ooo+     sNNo ",
		"{RD}        +oooo\\`",
]

[android]
margin = [2, 2, 2,]
art    = [
    "{GN}  ;,           ,;  ",
    "{GN}   ';,.-----.,;'   ",
    "{GN}  ,'           ',  ",
    "{GN} /    O     O    \\ ",
    "{GN}|                 |",
    "{GN}'-----------------'",
]

[arch]
margin = [2, 2, 3,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /\\   \\    ",
    "{BE}   /      \\   ",
    "{BE}  /   ,,   \\  ",
    "{BE} /   |  |  -\\ ",
    "{BE}/_-''    ''-_\\",
]

[arch_old]
margin = [1, 2, 3,]
art    = [
"(BE)     -+*##*+-        ",  
"(BE)   -+#######*={BK}:      ",
"(BE)  -+*******+++={BK}+*+   ",
"(BE) -++++++++=====- {BK}**+-",
"(BE) =++==+     =====-{BK}-==",
"(BE)+++++         +++-{BK}---",
"(BE)++++        {BK}+++(BE)+++{BK}=  ",
"(BE)****   {BK}******+  (BE)**   ",
"(BE)***              *   ",
]

[archbang]
margin = [3, 2, 3,]
art    = [
    "{CN}        /\\        ",
    "{CN}       / _\\       ",
    "{CN}      /  \\ /      ",
    "{CN}     /   // \\     ",
    "{CN}    /   //   \\    ",
    "{CN}   / ___()___ \\   ",
    "{CN}  /.\\`      `/.\\  ",
]

[archcraft]
margin = [2, 2, 3,]
art    = [
    "{GN}      .      ",
    "{GN}     / \\     ",
    "{GN}    /\\  \\    ",
    "{GN}   /     \\   ",
    "{GN}  / , ^ , \\  ",
    "{GN} /  <   > -\\ ",
    "{GN}/_-''   ''-_\\",
]

[arco]
alias = "arcolinux"
margin = [1, 2, 2,]
art    = [
    "{BE}          A          ",
    "{BE}         ooo         ",
    "{BE}        ooooo        ",
    "{BE}       ooooooo       ",
    "{BE}      ooooooooo      ",
    "{BE}     ooooo ooooo     ",
    "{BE}    ooooo   ooooo    ",
    "{BE}   ooooo     ooooo   ",
    "{BE}  ooooo  {GN}oooooooooo  ",
    "{BE} ooooo      {GN}oooooooo ",
    "{BE}ooooo          {GN}oooooo",
]

[artix]
margin = [2,2,2,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /`'.,\\    ",
    "{BE}   /     ',   ",
    "{BE}  /      ,`\\  ",
    "{BE} /   ,.'`.  \\ ",
    "{BE}/.,'`     `'.\\",
]

### B ####
[bedrock]
margin = [4, 3, 3,]
art    = [
		"{WE}__       ",
		"{WE}\\ \\___   ",
		"{WE} \\  _ \\  ",
		"{WE}  \\___/  ",
]

[buildroot]
margin = [3, 3, 3,]
art    = [
		"{YW}   ___     ",
		"{YW} / \\`   \\  ",
		"{YW}|   :  :|  ",
		"{YW} -. _:__.- ",
		"{YW} \\` ---- \\`"
]

### C ####
[cachy]
alias  = "cachyos"
margin = [2, 2, 2,]
art    = [
    "{CN}   /''''''''''''/  ",
    "{CN}  /''''''''''''/   ",
    "{CN} /''''''/          ",
    "{CN}/''''''/           ",
    "{CN}\\......\\           ",
    "{CN} \\......\\          ",
    "{CN}  \\.............../",
    "{CN}   \\............./ ",
]

[centos]
margin = [2, 3, 2]
art    = [
    "{GN} ____{YW}^{MA}____  ",
		"{GN} |\\  {YW}|{MA}  /|  ",
		"{GN} | \\ {YW}|{MA} / |  ",
		"{MA}<---- {BE}----> ",
		"{BE} | / {GN}|{YW} \\ |  ",
		"{BE} |/__{GN}|{YW}__\\|  ",
		"{GN}     v      ",
]

[crux]
margin = [2, 2, 3,]
art    = [
    "{BE}    ___   ",
    "{BE}   (.· |  ",
    "{BE}   ({YW}<>{BE} |  ",
    "{BE}  / {WE}__{BE}  \\ ",
    "{BE} ( {WE}/  \\{BE} /|",
    "{YW}_/\\{WE}(__){YW}/_)",
    "{YW}\\/{BE}-____{YW}\\/ ",
]

[crystal]
margin = [2, 2, 2,]
art    = [
		"(MA)        -//. ",
		"(MA)      -//.   ",
		"(MA)    -//. .   ",
		"(MA)  -//.  '//- ",
		"(MA) /+:      :+/",
		"(MA)  .//'  .//. ",
		"(MA)    . .//.   ",
		"(MA)    .//.     ",
    "(MA)  .//.       ",
]

### D ###
[dahlia]
alias  = "dahliaos"
margin = [1, 4, 3,]
art    = [
		"{RD}      _       ",
		"{RD}  ___/ \\___   ",
		"{RD} |   _-_   |  ",
		"{RD} | /     \\ |  ",
		"{RD}/ |       | \\ ",
		"{RD}\\ |       | / ",
		"{RD} | \\ _ _ / |  ",
		"{RD} |___ - ___|  ",
		"{RD}     \\_/      ",
]

[debian]
margin = [1, 2, 3,]
art    = [
    "(RD)  , - = - ,   ",
    "(RD) =    ,,   =  ",
    "(RD)=   :°   ;  = ",
    "(RD)=   :.      = ",
    "(RD)^=    ° == °  ",
    "(RD)°=.           ",
    "(RD) ^==..        ",
    "(RD)   ^^°==..    ",
    "(RD)        ^^°=  ",
]

[deepin]
margin = [2, 2, 2,]
art    = [
    "{BE}    ____________    ",
    "{BE}   /  /  /   ___\\   ",
    "{BE}  /   | / __/ ___\\  ",
    "{BE} /     \\/ / /     \\ ",
    "{BE}|        \\   \\     |",
    "{BE} \\_______/  _/    / ",
    "{BE}  \\________/     /  ",
    "{BE}   \\____________/   ",
]

[devuan]
margin = [2, 2, 2,]
art    = [
    "..:::.      ",
    "    ..-==-  ",
    "        .+#:",
    "         =@@",
    "      :+%@#:",
    ".:=+#@@%*:  ",
    "@@@@#=:     ",
]

[dragonfly]
alias  = "dragonflybsd"
margin = [2, 3, 2,]
art    = [
		 "   ,{RD}_{WE},    ",
		 "('-_{RD}|{WE}_-') ",
		 " >--{RD}|{WE}--<  ",
  	 "(_-'{RD}|{WE}'-_) ",
		 "    {RD}|     ",
		 "    {RD}|     ",
		 "    {RD}|     ",
]

### E ###
[elementary]
alias  = "elementaryos"
margin = [2, 2, 3,]
art    = [
    "{WE}  _______  ",
    "{WE} / ____  \\ ",
    "{WE}/  |  /  /\\",
    "{WE}|__\\ /  / |",
    "{WE}\\   /__/  /",
    "{WE} \\_______/ ",
]

[endeavour]
alias = "endeavouros"
margin = [2, 2, 3,]
art    = [
    "{MA}       /\\     ",
    "{RD}     /{MA}/  \\{CN}\\   ",
    "{RD}    /{MA}/    \\{CN}\\  ",
    "{RD}  / {MA}/     _) {CN})",
    "{RD} /_{MA}/___-- {CN}__- ",
    "{CN}/____--       ",
]

[evolution]
alias  = "evolutionos"
margin = [2, 3, 3,]
art    = [
    "{GN}      $2,coddoc'                ",
    "{GN}   'cddddddddddc'               ",
    "{GN} 'ddd$1OWWXXXXXXK$2ddo.         ",
    "{GN}.dddd$1OMX$2ddddddddddd.        ",
    "{GN}odddd$1OMX$2k$100O$2k$1OO$2ddddo",
    "{GN}.dddd$1OMX$2kOOOxOkdddd.        ",
    "{GN} .ddd$1OWW$2X$1XXXXXK$2ddd'     ",
    "{GN}   'dddddddddddd'               ",
    "{GN}      'cddddd,                  "
]

### F ###
[fedora]
margin = [1, 2, 3,]
art    = [
    "(WE)       _____  ",
    "(WE)     /   __)(BE)\\ ",
    "(WE)     |  /  (BE)\\ \\",
    "(BE)  __(WE)_|  |_(BE)_/ /",
    "(BE) / (WE)(_    _)(BE)_/ ",
    "(BE)/ /  (WE)|  |     ",
    "(BE)\\ \\(WE)__/  |     ",
    "(BE) \\(WE)(_____/     ",

]

[freebsd]
margin = [2, 4, 2,]
art    = [
		"{RD}/\\,-'''''-,/\\  ",
  	"{RD}\\_)       (_/  ",
		"{RD}|           |  ",
		"{RD}|           |  ",
		" {RD};         ;   ",
		"  {RD}'-_____-'    ",
]

### G ###
[garuda]
margin = [3, 2, 3,]
art    = [
    "(MA)     .----.   ",
    "(MA)   .'   ,  '. ",
    "(MA) .'    '-----|",
    "(MA)'.   -----,   ",
    "(MA)  '.____.'    ",
]

[gentoo]
margin = [2, 2, 3,]
art    = [
    "{MA} _-----_   ",
    "{MA}(       \\  ",
    "{MA}\\    0   \\ ",
    "{WE} \\        )",
    "{WE} /      _/ ",
    "{WE}(     _-   ",
    "{WE}\\____-     ",
]

[guix]
margin = [3, 2, 3,]
art    = [
    "{YW}|.__          __.| ",
    "{YW}|__ \\        / __| ",
    "{YW}   \\ \\      / /    ",
    "{YW}    \\ \\    / /     ",
    "{YW}     \\ \\  / /      ",
    "{YW}      \\ \\/ /       ",
    "{YW}       \\__/        ",
]

### H ###
[hyperbola]
margin = [2, 2, 3]
art = [
    "    |`__.`/  ",
    "    \\____/   ",
    "    .--.     ",
    "   /    \\    ",
    "  /  ___ \\   ",
    " / .`   `.\\  ",
    "/.`      `.\\ ",
]

### I ###
[iglunix]
margin = [0, 2, 2,]
art    = [
    "       |              ",
		"       |          |   ",
		"                  |   ",
		"  |    ________       ",
		"  |  /\\   |    \\      ",
		"    /  \\  |     \\  |  ",
		"   /    \\        \\ |  ",
		"  /      \\________\\   ",
		"  \\      /        /   ",
		"   \\    /        /    ",
		"    \\  /        /     ",
		"     \\/________/      ",
]

[instant]
alias  = "instantos"
margin = [3, 2, 2,]
art    = [
		"{WE} ,-''-,      ",
		"{WE}: .''. :     ",
		"{WE}: ',,' :     ",
		"{WE} '-____:__   ",
		"{WE}       :  \\`.",
		"{WE}       \\`._.'",
]

### J ###

### K ###
[kali]
margin = [0, 1, 2]
art    = [
    "{BE}        ⢀ ⡀        ",
    "{BE}     ⢀⡀⢀⡀⢣⡐⣄       ",
    "{BE}  ⢤⣬⣿⣿⣿⣿⣿⣶⣿⣮⣷⣄     ",
    "{BE} ⢴⣿⣿⠛⠉  ⠈⠉⠻⣿⣿⣿⣷⣄   ",
    "{BE}⢠⣿⣿⡇        ⢿⣿⣦⣿⣦  ",
    "{BE} ⡸⣿⣷⡀        ⠙⠻⣿⣷⡀ ",
    "{BE}  ⠸⠻⣿⣦⡀        ⠈⢻⣿⠇",
    "{BE}     ⠉⠛⠷⣦⣄⡀     ⠈⠁ ",
    "{BE}         ⠉⠛⢷⣄      ",
    "{BE}            ⠈⢿     ",
]

[neon]
alias  = "kdeneon"
margin = [3, 3, 3,]
art    = [
    "{GN}    --- _   ",
    "{GN} /  ---  \\  ",
    "{GN}|  |   |  | ",
    "{GN} \\  --- _/  ",
    "{GN}    ---     ",
]

### L ###  
[lite]
alias  = "linuxlite"
margin = [3, 3, 4,]
art    = [
		"{YW}   /\\ ",
		"{YW}  /  \\",
		"{YW} / {WE}/ {YW}/",
		"{YW}> {WE}/ {YW}/ ",
		"{YW}\\ {WE}\\ {YW}\\ ",
		" {YW}\\_{WE}\\{YW}_\\",
		"{WE}    \\ ",
]


### M ###
[macos]
margin = [2, 4, 2,]
art    = [
		"{GN}       .:'      ",
		"{GN}    _ :'_       ",
		"{YW} .'\\`_\\`-'_\\`.  ",
		"{RD}:________.-'    ",
		"{RD}:________:      ",
		"{MA} :_______\\`-;   ",
		"{BE}  \\`._.-._.'    ",
]

[mageria]
margin = [2, 4, 3,]
art    = [
		"{BE}   *     ",
		"{BE}    *    ",
		"{BE}   **    ",
		"{BK} /\\__/\\  ",
		"{BK}/      \\ ",
		"{BK}\\      / ",
		"{BK} \\____/  ",
]

[manjaro]
margin = [2, 2, 4,]
art    = [
    "<GN>        !DT!  <GN>    ",
    "<GN>        !DT!  <GN>    ",
    "<GN>   !DT!       <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
]

[mint]
alias = "linuxmint"
margin = [2, 2, 4,]
art    = [
    "{CN} ___________ ",
    "{CN}|_          \\",
    "{CN}  | (WE)| _____ {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)\\_____/ {CN}|",
    "{CN}  \\_________/",
]

[mx]
margin = [2, 2, 2,]
art    = [
    "{WE}    \\\\  /    ",
    "{WE}     \\\\/     ",
    "{WE}      \\\\     ",
    "{WE}   /\\/ \\\\    ",
    "{WE}  /  \\  /\\   ",
    "{WE} /    \\/  \\  ",
    "{WE}/__________\\ ",
]


### N ###
[netbsd]
margin = [2, 2, 2,]
art    = [
		"{WE}\\\\{YW}\\`-______,----__  ",
		"{WE} \\\\        {YW}__,---\\`_",
		"{WE}  \\\\       {YW}\\`.____  ",
		"{WE}   \\\\{YW}-______,----\\`-",
		"{WE}    \\\\              ",
		"{WE}     \\\\             ",
		"{WE}      \\\\            ",
]

[nobara]
margin = [2, 2, 2,]
art    = [
		"{WE} _._.  _..,._          ",
		"{WE}|##############.       ",
		"{WE}|################.     ",
		"{WE}|#####/  .  \\#####.    ",
		"{WE}|####|  ###   > ###    ",
		"{WE}|#####  \\`\\`\\`|##### ",
		"{WE}|######==_   |#####    ",
		"{WE}|######\"##|  |#####    ",
		"{WE} \\`\"\"\\`\\` '  \\`\\##/ ",
]

[none]
margin = [0, 0, 0,]
art = [""]

[nixos]
margin = [1, 2, 3,]
art    = [
    "{BE}     ⣀⡀  {CN}⣀⣀⡀ ⢀⣀     ",
    "{BE}    ⠈⢿⣷⡀ {CN}⠈⢿⣷⣄⣾⡿⠃    ",
    "{BE}  ⢀⣶⣶⣾⣿⣿⣶⣶⣮{CN}⣻⣿⣿⠁ {BE}⢠⡀  ",
    "{CN}     ⣩⣭⡍    ⢻⣿⣆{BE}⢠⣿⡗  ",
    "{CN}⢠⣤⣤⣤⣴⣿⠟      ⠹{BE}⣳⣿⣿⣤⣤⡄",
    "{CN}⠘⠛⠛⣿⣿⢯{BE}⣦      ⣰⣿⠟⠛⠛⠛⠃",
    "{CN}  ⢼⣿⠋{BE}⠹⣿⣧{CN}⢀⣀⣀⣀⣜⣛⣋⣀⣀⡀  ",
    "{CN}  ⠈⠃ {BE}⢀⣾⣿⣷{CN}⡻⠿⠿⢿⣿⡿⠿⠿⠁  ",
    "{BE}    ⢠⣾⡿⠙⢿⣷⡀ {CN}⠈⢿⣷⡄    ",
    "{BE}     ⠉⠁ ⠈⠉⠉  {CN}⠈⠉     ",
]

### O ###
[openbsd]
margin = [2, 2, 3,]
art    = [
		"{YW}      _____    ",
		"{YW}    \\-     -/  ",
		"{YW} \\_/         \\ ",
		"{YW} |        {WE}O O{YW} |",
		"{YW} |_  <   )  3 )",
		"{YW} / \\         / ",
		" {YW}   /-_____-\\  ",
]

[opensuse]
margin = [0, 0, 2,]
art    = [
    "!DT!           .;ldkO0000Okdl;.           ",
    "!DT!       .;d00xl:^''''''^:ok00d;.       ",
    "!DT!     .d00l'                'o00d.     ",
    "!DT!   .d0Kd'  (GN)Okxol:;,.          !DT!:O0d.   ",
    "!DT!  .OK(GN)KKK0kOKKKKKKKKKKOxo:,      !DT!lK0.  ",
    "!DT! ,0K(GN)KKKKKKKKKKKKKKKOP^!DT!,,,(GN)^dx:    !DT!;OO, ",
    "!DT!.OK(GN)KKKKKKKKKKKKKKKk'!DT!.oOPPb.(GN)'Ok.   !DT!cKO.",
    "!DT!:KK(GN)KKKKKKKKKKKKKKK: !DT!kKx..dd (GN)lKd   !DT!'OK:",
    "!DT!dKK(GN)KKKKKKKKKOxOKKKd !DT!^OKKKO' (GN)kKKc   !DT!dKd",
    "!DT!dKK(GN)KKKKKKKKKK;.;oOKx,..!DT!^(GN)..;kKKKO.  !DT!dKd",
    "!DT!:KK(GN)KKKKKKKKKK0o;...^cdxxOK0O/^^'  !DT!.OK:",
    "!DT! kKK(GN)KKKKKKKKKKKKKOx;,,......,;od  !DT!lKk ",
    "!DT! '0K(GN)KKKKKKKKKKKKKKKKKKKK00KKOo^  !DT!c00' ",
    "!DT!  'kK(GN)KKOxddxkOO00000Okxoc;''   !DT!.dKk'  ",
    "!DT!    l0Ko.                    .c00l'   ",
    "!DT!     'l0Kk:.              .;xK0l'     ",
    "!DT!        'lkK0xl:;,,,,;:ldO0kl'        ",
    "!DT!            '^:ldxkkkkxdl:^'          "
]

### P ###
[parabola]
margin = [2, 2, 2,]
art    = [
    "  __ __ __  _  ",
    "`_//_//_/ / `. ",
    "          /  .`",
    "         / .`  ",
    "        /.`    ",
    "       /`      ",
]

[pop]
alias = "popos, pop_os"
margin = [1, 1, 2,]
art    = [
    "{CN}  ______             ",
    "{CN}  \\   _ \\        __  ",
    "{CN}   \\ \\ \\ \\      / /  ",
    "{CN}    \\ \\_\\ \\    / /   ",
    "{CN}     \\  ___\\  /_/    ",
    "{CN}      \\ \\    _       ",
    "{CN}     __\\_\\__(_)_     ",
    "{CN}    (___________)    ",
]

[postmarketos]
margin = [2, 2, 2,]
art    = [
    "{GN}        /\\        ",
    "{GN}       /  \\       ",
    "{GN}      /    \\      ",
    "{GN}      \\__   \\     ",
    "{GN}    /\\__ \\  _\\    ",
    "{GN}   /   /  \\/ __   ",
    "{GN}  /   / ____/  \\  ",
    "{GN} /    \\ \\       \\ ",
    "{GN}/_____/ /________\\",
]

[pureos]
margin = [3, 2, 2,]
art    = [
    " _____________ ",
    "|  _________  |",
    "| |         | |",
    "| |         | |",
    "| |_________| |",
    "|_____________|",
]

### Q ###

### R ###
[raspbian]
alias = "raspberrypios"
margin = [2, 2, 3,]
art    = [
    "{GN}  __  __   ",
    "{GN} (_\\)(/_)  ",
    "{RD} (_(__)_)  ",
    "{RD}(_(_)(_)_) ",
    "{RD} (_(__)_)  ",
    "{RD}   (__)    ",
]

[reborn]
alias  = "rebornos"
margin = [2, 3, 3,]
art    = [
    "{BE}   _______   ",
    "{BE}  /\\_____/\\  ",
    "{BE} / /\\___/\\ \\ ",
    "{BE}/_/_/   \\_\\_\\",
    "{BE}\\ \\ \\___/ / /",
    "{BE} \\ \\/___\\/ / ",
    "{BE}  \\/_____\\/  ",
]

[rocky]
margin = [1, 2, 3]
art    = [
    "{GN}    `-/+++++++++/-.`     ",
    "{GN} `-+++++++++++++++++-`   ",
    "{GN}.+++++++++++++++++++++.  ",
    "{GN}-+++++++++++++++++++++++.",
    "{GN}+++++++++++++++/-/+++++++",
    "{GN}+++++++++++++/.   ./+++++",
    "{GN}+++++++++++:.       ./+++",
    "{GN}+++++++++:`   `:/:`   .:/",
    "{GN}-++++++:`   .:+++++:`    ",
    "{GN} .+++-`   ./+++++++++:`  ",
    "{GN}  `-`   ./+++++++++++-   ",
    "{GN}       -+++++++++:-.`    ",
]

### S ###
[slackware]
margin = [2, 2, 3,]
art    = [
    "{BE}   ________  ",
    "{BE}  /  ______| ",
    "{BE}  | |______  ",
    "{BE}  \\______  \\ ",
    "{BE}   ______| | ",
    "{BE}| |________/ ",
    "{BE}|____________",
]

[solus]
margin = [3, 2, 2,]
art    = [
		"{BE}     /|       ",
		"{BE}    / |\\      ",
		"{BE}   /  | \\ _   ",
		"{BE}  /___|__\\_\\  ",
		"{BE}  \\         / ",
		"{BE}   \\-------´  ",
]

[sourcemage]
margin = [0, 2, 3]
art    = [
    "       :ymNMNho.              ",
    ".+sdmNMMMMMMMMMMy`            ",
    ".-::/yMMMMMMMMMMMm-           ",
    "      sMMMMMMMMMMMm/          ",
    "     /NMMMMMMMMMMMMMm:        ",
    "    .MMMMMMMMMMMMMMMMM:       ",
    "    `MMMMMMMMMMMMMMMMMN.      ",
    "     NMMMMMMMMMMMMMMMMMd      ",
    "     mMMMMMMMMMMMMMMMMMMo     ",
    "     hhMMMMMMMMMMMMMMMMMM.    ",
    "     .`/MMMMMMMMMMMMMMMMMs    ",
    "        :mMMMMMMMMMMMMMMMN`   ",
    "         `sMMMMMMMMMMMMMMM+   ",
    "           /NMMMMMMMMMMMMMN`  ",
    "             oMMMMMMMMMMMMM+  ",
    "          ./sd.-hMMMMMMMMmmN` ",
    "      ./+oyyyh- `MMMMMMMMMmNh ",
    "                 sMMMMMMMMMmmo",
    "                 `NMMMMMMMMMd:",
    "                  -dMMMMMMMMMo",
    "                    -shmNMMms.",
]

### T ###
[tux]
alias = "default"
margin = [2, 2, 3,]
art    = [
    "(BK)      .--.     ",
    "(BK)     |!DT!o(BK)_!DT!o (BK)|    ",
    "(BK)     |(YW):_/ (BK)|    ",
    "(BK)    /!DT!/   \\ (BK)\\   ",
    "(BK)   (!DT!|     | (BK))  ",
    "(YW)  /'!DT!|_   _/(YW)'\\  ",
    "(YW)  \\___)(BK)=(YW)(___/  ",
]

### U ###
[ubuntu]
margin = [0, 2, 4,]
art    = [
    "{RD}                .-.   ",
    "{RD}        .-'````(   )  ",
    "{RD}     ,`\\ \\    `-`.    ",
    "{RD}    /   \\ '````-.   ` ",
    "{RD}  .-.  ,         `___:",
    "{RD} (   ) :          ___ ",
    "{RD}  `-`  `         ,   :",
    "{RD}    \\   / ,....-`   , ",
    "{RD}     `./ /      .-.`  ",
    "{RD}        `-....-(   )  ",
    "{RD}                `-`   ",
]

### V ###
[vanilla]
alias  = "vanillaos"
margin = [2, 2, 2,]
art    = [
		"{YW}        .#.           ",
		"{YW}       :#=#:          ",
		"{YW}.#=\":.:##=##:.:\"=#.   ",
		"{YW}\\`:#=#####=####=##:\\` ",
		"{YW} \\`:####=\\` \\`=####:\\`",
		"{YW}   .:##,. .,##:.      ",
	  "{YW}  :##=##:-:##=##:     ",
		"{YW} .#=##:\\`   \\`:##=#.  ",
		"{YW}  \\`\\`           \\`\\` ",
]

[venom]
margin = [1, 2, 3,]
art    = [
    "{WE} ++**               ",
    "{WE}  *===**====+*      ",
    "{WE}   *====*   +===+   ",
    "{WE} *==*+===*    *===* ",
    "{WE}*===* *===+    *===*",
    "{WE}*===*  +===+   *===*",
    "{WE}*===*   +===*  *===*",
    "{WE} *===*    *===+*==* ",
    "{WE}   +===+   *===+=*  ",
    "{WE}      *+====**===*  ",
    "{WE}               **++ ",
]

[void]
margin = [2, 2, 4,]
art    = [
    "(GN)    _______  ",
    "(GN) _ \\______ - ",
    "(GN)| \\  ___  \\ |",
    "(GN)| | /   \\ | |",
    "(GN)| | \\___/ | |",
    "(GN)| \\______ \\_|",
    "(GN) -_______\\   ",
]

[voyager]
margin = [2, 2, 2,]
art    = [
    "{RD} _____   ____ ",
    "{RD}|     | |    |",
    "{RD}|     | |    |",
    "{RD}|     | |    |",
    "{RD}|     | |____|",
    "{RD}|     | _____ ",
    "{RD}|     ||     |",
    "{RD}|_____||_____|",

]

### W ###

### X ###
[xero]
alias  = "xerolinux"
margin = [3, 2, 2,]
art    = [
    "{WE}        /\\       ",
    "{WE}______ /  \\______",
    "{WE}      /\\  /\\     ",
    "{WE}     /  ||  \\    ",
    "{WE}____/__/__\\__\\___",
    "{WE}   / __|  |__-\\  ",
    "{WE}  /_-''    ''-_\\ ",
]

### Y ###

### Z ###
[zorin]
margin = [1, 1, 2]
art    = [
    "(BE)    ⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆    ",
    "(BE)   ⠐⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠂   ",
    "(BE)                    ",
    "(BE) ⣴⣿⣿⣿⣿⣿⣿⣿⡿⠟⠋⠁  ⣀⣤⣶⣦ ",
    "(BE)⢼⣿⣿⣿⣿⣿⠿⠋⠁  ⢀⣠⣶⣿⣿⣿⣿⣿⡇",
    "(BE) ⠹⣿⠛⠉   ⣀⣴⣾⣿⣿⣿⣿⣿⣿⣿⠟ ",
    "(BE)                    ",
    "(BE)   ⠠⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⠄   ",
    "(BE)    ⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏    ",
]
