# THIS IS THE CONFIG FILE USED TO TEST CATNAP!
# PLEASE MAKE SURE, EVERY STAT IS ACTIVATE!
# ALWAYS ADD NEWLY ADDED STATS HERE!

[stats]
username  = {icon = ">", name = "user", color = "(RD)"}
hostname  = {icon = ">", name = "hname", color = "(YW)"}
uptime    = {icon = ">", name = "uptime", color = "(BE)"}
distro    = {icon = ">", name = "distro", color = "(GN)"}
kernel    = {icon = ">", name = "kernel", color = "(MA)"}
desktop   = {icon = ">", name = "desktp", color = "(CN)"}
terminal  = {icon = ">", name = "term", color = "(RD)"}
shell     = {icon = ">", name = "shell", color = "(MA)"}
packages  = {icon = ">", name = "packages", color = "(GN)"}
gpu       = {icon = ">", name = "gpu", color = "(MA)"}
cpu       = {icon = ">", name = "cpu", color = "(RD)"}
disk_0    = {icon = ">", name = "disk", color = "(GN)"}
memory    = {icon = ">", name = "memory", color = "(YW)"}
sep_color = "SEPARATOR"
colors    = {icon = "> ", name = "colors", color = "!DT!", symbol = "#"}

##############################################

[misc]
borderstyle = "doubleline"
layout = "Inline"
stats_margin_top = 0
location = "San Francisco"
