name: build-test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Install Nim'
      uses: iffy/install-nim@v5
    - name: 'Setup Nim'
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '2.x'
    - name: 'Build Catnip'
      run: nim release
    - name: 'Install Figlet'
      run: sudo apt-get install figlet
    - name: 'Run Tests'
      run: cd tests && ./test.sh
    - name: 'Add build Number'
      run: echo 'const BUILDNUMBER* = "${{ github.run_id }}"' > ./src/catniplib/global/buildnum.nim
    - name: 'Push build Number'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "Automatic build Number update"
        git push
